/**
 * Forum-ready build sheets.
 *
 * Raptor owners already keep build lists by hand, in forum posts and
 * signatures. This renders the same list from data the app already has, in
 * the markup those forums actually take.
 *
 * Privacy is the load-bearing decision here: VIN, purchase price, seller, and
 * insurance details are never eligible for output, and costs are opt-in and
 * off by default. A build list is meant to be public; what the truck cost is
 * not, and a share feature that leaks it by default is worse than no feature.
 */

// Order categories the way people describe a build, not alphabetically.
const CATEGORY_ORDER = [
  'Suspension', 'Tires_Wheels', 'Bumpers', 'Armor', 'Lighting', 'Electrical',
  'Performance', 'Engine', 'Recovery', 'Bed_Accessories', 'Audio', 'Interior', 'Other',
];

const label = (c) => String(c || 'Other').replace(/_/g, ' ');
const money = (n) => `$${Number(n).toLocaleString('en-US', { maximumFractionDigits: 0 })}`;
const num = (n) => Number(n).toLocaleString('en-US');

function orderCategories(cats) {
  return [...cats].sort((a, b) => {
    const ia = CATEGORY_ORDER.indexOf(a), ib = CATEGORY_ORDER.indexOf(b);
    return (ia === -1 ? 99 : ia) - (ib === -1 ? 99 : ib) || a.localeCompare(b);
  });
}

/**
 * Pull only what is safe to publish. Anything not selected here cannot leak
 * into a build sheet by accident later.
 */
function gather(db, vehicleId) {
  const v = db.prepare(`
    SELECT uv.nickname, uv.model_year, uv.color, uv.current_mileage,
           veh.make, veh.model, veh.generation, veh.variant
    FROM user_vehicles uv JOIN vehicles veh ON uv.vehicle_id = veh.id
    WHERE uv.id = ?
  `).get(vehicleId);
  if (!v) return null;

  const mods = db.prepare(`
    SELECT part_name, brand, part_number, vendor, vendor_url, category, cost,
           install_date, aux_switches
    FROM mods
    WHERE user_vehicle_id = ? AND status = 'Installed'
    ORDER BY category, part_name
  `).all(vehicleId).map(m => {
    let switches = [];
    try {
      switches = JSON.parse(m.aux_switches || '[]')
        .map(s => parseInt(s.switch_number, 10)).filter(n => !isNaN(n)).sort((a, b) => a - b);
    } catch (_) { switches = []; }
    return { ...m, switches };
  });

  return { vehicle: v, mods };
}

function title(v) {
  const base = [v.model_year, v.make, v.model, v.variant].filter(Boolean).join(' ');
  return v.nickname ? `${base} — "${v.nickname}"` : base;
}

function subtitleParts(v, opts) {
  const parts = [];
  if (v.generation) parts.push(v.generation);
  if (v.color) parts.push(v.color);
  if (opts.includeMileage && v.current_mileage) parts.push(`${num(v.current_mileage)} miles`);
  return parts;
}

function grouped(mods) {
  const byCat = new Map();
  for (const m of mods) {
    const c = m.category || 'Other';
    if (!byCat.has(c)) byCat.set(c, []);
    byCat.get(c).push(m);
  }
  return orderCategories([...byCat.keys()]).map(c => [c, byCat.get(c)]);
}

// One mod, rendered as its descriptive line. Brand leads because that's how
// people talk about parts: "Fox 3.0", not "3.0 by Fox".
function modLine(m, opts) {
  let line = [m.brand, m.part_name].filter(Boolean).join(' ');
  const extra = [];
  if (opts.includePartNumbers && m.part_number) extra.push(`PN ${m.part_number}`);
  if (opts.includeAux && m.switches.length) {
    extra.push(`AUX ${m.switches.join(' + ')}`);
  }
  if (opts.includeCosts && m.cost != null) extra.push(money(m.cost));
  if (extra.length) line += ` (${extra.join(', ')})`;
  return line;
}

const DEFAULTS = {
  includeCosts: false,        // deliberately off — a build list is public, a budget isn't
  includeMileage: true,
  includePartNumbers: false,
  includeAux: true,
  includeAttribution: true,
};

function render(data, format, options = {}) {
  const opts = { ...DEFAULTS, ...options };
  const { vehicle: v, mods } = data;
  const groups = grouped(mods);
  const sub = subtitleParts(v, opts);
  const total = mods.reduce((s, m) => s + (m.cost || 0), 0);
  const withCost = mods.filter(m => m.cost != null).length;

  const out = [];

  if (format === 'bbcode') {
    out.push(`[b][size=4]${title(v)}[/size][/b]`);
    if (sub.length) out.push(sub.join(' · '));
    out.push('');
    for (const [cat, list] of groups) {
      out.push(`[b]${label(cat).toUpperCase()}[/b]`);
      out.push('[list]');
      for (const m of list) {
        const line = modLine(m, opts);
        out.push(`[*]${m.vendor_url && opts.includeLinks ? `[url=${m.vendor_url}]${line}[/url]` : line}`);
      }
      out.push('[/list]');
      out.push('');
    }
    if (opts.includeCosts && withCost) {
      out.push(`[b]Total (${withCost} of ${mods.length} parts priced):[/b] ${money(total)}`);
      out.push('');
    }
    if (opts.includeAttribution) {
      out.push('[size=1]Build list generated by [url=https://github.com/breed007/RaptorTracker]RaptorTracker[/url][/size]');
    }
  } else if (format === 'markdown') {
    out.push(`## ${title(v)}`);
    if (sub.length) out.push(`*${sub.join(' · ')}*`);
    out.push('');
    for (const [cat, list] of groups) {
      out.push(`### ${label(cat)}`);
      for (const m of list) {
        const line = modLine(m, opts);
        out.push(`- ${m.vendor_url && opts.includeLinks ? `[${line}](${m.vendor_url})` : line}`);
      }
      out.push('');
    }
    if (opts.includeCosts && withCost) {
      out.push(`**Total (${withCost} of ${mods.length} parts priced):** ${money(total)}`);
      out.push('');
    }
    if (opts.includeAttribution) {
      out.push('<sub>Build list generated by [RaptorTracker](https://github.com/breed007/RaptorTracker)</sub>');
    }
  } else { // plain text
    out.push(title(v));
    if (sub.length) out.push(sub.join(' · '));
    out.push('');
    for (const [cat, list] of groups) {
      out.push(`${label(cat).toUpperCase()}`);
      for (const m of list) out.push(`  - ${modLine(m, opts)}`);
      out.push('');
    }
    if (opts.includeCosts && withCost) {
      out.push(`Total (${withCost} of ${mods.length} parts priced): ${money(total)}`);
      out.push('');
    }
    if (opts.includeAttribution) {
      out.push('Build list generated by RaptorTracker — github.com/breed007/RaptorTracker');
    }
  }

  // Collapse the trailing blank lines a per-group push leaves behind.
  while (out.length && out[out.length - 1] === '') out.pop();
  return out.join('\n');
}

function buildSheet(db, vehicleId, format = 'bbcode', options = {}) {
  const data = gather(db, vehicleId);
  if (!data) return null;
  const fmt = ['bbcode', 'markdown', 'text'].includes(format) ? format : 'bbcode';
  return {
    format: fmt,
    modCount: data.mods.length,
    content: render(data, fmt, options),
  };
}

module.exports = { buildSheet, DEFAULTS, CATEGORY_ORDER };
